# -*- coding: utf-8 -*-
"""Untitled35.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WRcIK6VajjKoFKnB8-6VQxoKsB6zl8h4
"""

import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd
import numpy as np

# Example data
data = pd.DataFrame({
    'Age': np.random.randint(10, 70, size=100),
    'Gender': np.random.choice(['Male', 'Female'], size=100)
})

# Plot histogram for Age (continuous variable)
plt.figure(figsize=(8, 5))
sns.histplot(data['Age'], bins=10, kde=True, color='skyblue')
plt.title('Distribution of Ages')
plt.xlabel('Age')
plt.ylabel('Frequency')
plt.grid(True)
plt.show()

# Plot bar chart for Gender (categorical variable)
plt.figure(figsize=(6, 5))
sns.countplot(x='Gender', data=data, palette='Set2')
plt.title('Gender Distribution')
plt.xlabel('Gender')
plt.ylabel('Count')
plt.grid(True)
plt.show()